export const iconOptions = [
  { label: 'School', value: 'school' },
  { label: 'Graduation Cap', value: 'graduationCap' },
  { label: 'Book', value: 'book' },
  { label: 'Book Open', value: 'bookOpen' },
  { label: 'Library', value: 'library' },
  { label: 'Calendar', value: 'calendar' },
  { label: 'Clock', value: 'clock' },
  { label: 'Users', value: 'users' },
  { label: 'Sparkles', value: 'sparkles' },
  { label: 'Help Circle', value: 'helpCircle' },
  { label: 'Lightbulb', value: 'lightbulb' },
  { label: 'Heart', value: 'heart' },
  { label: 'Star', value: 'star' },
  { label: 'Shield', value: 'shield' },
  { label: 'Message Circle', value: 'messageCircle' },
  { label: 'Messages', value: 'messagesSquare' },
  { label: 'Award', value: 'award' },
  { label: 'Target', value: 'target' },
  { label: 'Compass', value: 'compass' },
  { label: 'Map', value: 'map' },
  { label: 'Globe', value: 'globe' },
  { label: 'Flask', value: 'flaskConical' },
  { label: 'Atom', value: 'atom' },
  { label: 'Brain', value: 'brain' },
  { label: 'Puzzle', value: 'puzzle' },
  { label: 'Palette', value: 'palette' },
  { label: 'Music', value: 'music' },
  { label: 'Mic', value: 'mic' },
  { label: 'Pencil', value: 'pencil' },
  { label: 'File Text', value: 'fileText' },
  { label: 'Calculator', value: 'calculator' },
  { label: 'Dumbbell', value: 'dumbbell' },
  { label: 'Leaf', value: 'leaf' },
  { label: 'Rocket', value: 'rocket' },
  { label: 'Briefcase', value: 'briefcase' },
  { label: 'Handshake', value: 'handshake' },
  { label: 'Arrow Right', value: 'arrowRight' },
  { label: 'Play', value: 'play' },
  { label: 'Check Circle', value: 'checkCircle' },
  { label: 'Home', value: 'home' },
  { label: 'Smile', value: 'smile' },
  { label: 'Phone', value: 'phone' },
  { label: 'Mail', value: 'mail' },
  { label: 'Facebook', value: 'facebook' },
  { label: 'Instagram', value: 'instagram' },
  { label: 'Twitter', value: 'twitter' },
  { label: 'YouTube', value: 'youtube' },
  { label: 'LinkedIn', value: 'linkedin' },
  { label: 'GitHub', value: 'github' },
  { label: 'Twitch', value: 'twitch' },
  { label: 'Slack', value: 'slack' },
  { label: 'GitLab', value: 'gitlab' },
  { label: 'Figma', value: 'figma' },
  { label: 'Dribbble', value: 'dribbble' },
  { label: 'CodePen', value: 'codepen' },
  { label: 'CodeSandbox', value: 'codesandbox' },
  { label: 'Trello', value: 'trello' },
  { label: 'Framer', value: 'framer' },
  { label: 'Pocket', value: 'pocket' },
  { label: 'At Sign', value: 'atSign' },
  { label: 'Share', value: 'share2' },
  { label: 'Music Note', value: 'music2' },
  { label: 'RSS', value: 'rss' },
] as const

export type IconName = (typeof iconOptions)[number]['value']

export const iconValues = iconOptions.map((option) => option.value)
