import React from 'react'
import {
  ArrowRight,
  AtSign,
  Atom,
  Award,
  Book,
  BookOpen,
  Brain,
  Briefcase,
  Calculator,
  Calendar,
  CheckCircle,
  Clock,
  Codepen,
  Codesandbox,
  Compass,
  Dribbble,
  Dumbbell,
  Facebook,
  Figma,
  FileText,
  FlaskConical,
  Framer,
  Github,
  Gitlab,
  Globe,
  GraduationCap,
  Handshake,
  Heart,
  HelpCircle,
  Home,
  Instagram,
  Leaf,
  Library,
  Lightbulb,
  Linkedin,
  Mail,
  Map,
  MessageCircle,
  MessagesSquare,
  Mic,
  Music,
  Music2,
  Palette,
  Pencil,
  Phone,
  Play,
  Pocket,
  Puzzle,
  Rocket,
  Rss,
  School,
  Share2,
  Shield,
  Slack,
  Smile,
  Sparkles,
  Star,
  Target,
  Trello,
  Twitch,
  Twitter,
  Users,
  Youtube,
  type LucideIcon,
} from 'lucide-react'

import type { IconName } from '@/utilities/iconOptions'

export const iconMap: Record<IconName, LucideIcon> = {
  arrowRight: ArrowRight,
  atSign: AtSign,
  atom: Atom,
  award: Award,
  book: Book,
  bookOpen: BookOpen,
  brain: Brain,
  briefcase: Briefcase,
  calculator: Calculator,
  calendar: Calendar,
  checkCircle: CheckCircle,
  clock: Clock,
  codepen: Codepen,
  codesandbox: Codesandbox,
  compass: Compass,
  dribbble: Dribbble,
  dumbbell: Dumbbell,
  facebook: Facebook,
  figma: Figma,
  fileText: FileText,
  flaskConical: FlaskConical,
  framer: Framer,
  github: Github,
  gitlab: Gitlab,
  globe: Globe,
  graduationCap: GraduationCap,
  handshake: Handshake,
  heart: Heart,
  helpCircle: HelpCircle,
  home: Home,
  instagram: Instagram,
  leaf: Leaf,
  library: Library,
  lightbulb: Lightbulb,
  linkedin: Linkedin,
  mail: Mail,
  map: Map,
  messageCircle: MessageCircle,
  messagesSquare: MessagesSquare,
  mic: Mic,
  music: Music,
  music2: Music2,
  palette: Palette,
  pencil: Pencil,
  phone: Phone,
  play: Play,
  pocket: Pocket,
  puzzle: Puzzle,
  rocket: Rocket,
  rss: Rss,
  school: School,
  share2: Share2,
  shield: Shield,
  slack: Slack,
  smile: Smile,
  sparkles: Sparkles,
  star: Star,
  target: Target,
  trello: Trello,
  twitch: Twitch,
  twitter: Twitter,
  users: Users,
  youtube: Youtube,
}

export type IconProps = {
  className?: string
  name?: IconName | (string & {}) | null
  size?: number | string
  style?: React.CSSProperties
}

export const Icon: React.FC<IconProps> = ({ className, name, size, style }) => {
  const IconComponent = (name && iconMap[name as IconName]) || School

  return <IconComponent className={className} size={size} style={style} />
}
